# # Setup
# title:        Project or Site name
# tagline:      A responsive theme for your project on GitHub Pages
# baseurl:      ""
# paginate:     1
# locale:       "en"

# # About/contact
# author:
#   name:       Author name
#   url:        http://yourhomepage.com 

# # Gems
# gems:
#   - jekyll-paginate

# #Others
# markdown: kramdown
theme: jekyll-theme-cayman
collections:
  pages:
    output: true

# Site Settings
locale                   : "en"
baseurl                  : ""
title                    : "ACL Student Research Workshop (SRW) 2026"
title_separator          : "-"
name                     : "ACL"
description              : "In conjunction with ACL 2026 in San Diego, US" 
breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "acl2026srw"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : # true, false (default)
search_full_content      : # true, false (ssdefault)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true

# Google services
# google_analytics: G-H0WTYZKZ8Y

# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :
# # Reading Files
# include : ['.htaccess', '_pages', ]

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: acl.2026.srw@gmail.com
  github: acl2026-srw
  twitter: acl_srw
  
